version: "3"

services:
  api.learning.com:
    build: ./api
    container_name: api.learning.com
    #command: ["npm", "start"] ## COMMENT this line to RUN with MP2 instead of NPM
    volumes:
      - ./api:/home/nodejs/app
      - /home/nodejs/app/node_modules
    networks:
      - tddnetwork
    ports:
      - 3000:3000
  mongo-instance:
    container_name: mongo-instance
    image: mongo:4.0.4
    environment:
      - appendonly=yes
      - TZ=US/Eastern
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - tddnetwork
volumes:
  mongo_data:
    driver: local
networks:
  tddnetwork:
    driver: bridge
