name: ci-api

on:
  push:
    branches:
      - master

jobs:
  ci-api:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Install api deps
        run: npm install
      - name: Run tests
        run: npm test
