name: ci-learning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  NODE_ENV: test
jobs:
  ci-api:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install api deps
        run: npm install
      - name: Run tests
        run: npm test
